CREATE TABLE member (
    id                      VARCHAR2(50) PRIMARY KEY,
    passwd                  VARCHAR2(255) NOT NULL,
    name                    VARCHAR2(100) NOT NULL,
    registrationnumber      VARCHAR2(30),
    address                 VARCHAR2(500),
    phonenumber             VARCHAR2(30),
    email                   VARCHAR2(255),
    grade                   VARCHAR2(30) DEFAULT 'BRONZE' NOT NULL,
    point                   NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE member_benefit (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id               VARCHAR2(50) NOT NULL,
    benefit_name            VARCHAR2(100) NOT NULL,
    benefit_description     VARCHAR2(500) NOT NULL,
    CONSTRAINT fk_benefit_member FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE menu (
    id                      NUMBER PRIMARY KEY,
    name                    VARCHAR2(100) NOT NULL,
    position                VARCHAR2(30) NOT NULL
);

CREATE TABLE products (
    product_id              NUMBER PRIMARY KEY,
    name                    VARCHAR2(200) NOT NULL,
    description             VARCHAR2(2000),
    price                   NUMBER(12, 2) NOT NULL,
    stock                   NUMBER(10) DEFAULT 0 NOT NULL,
    image_url               VARCHAR2(1000),
    image                   BLOB,
    image_type              VARCHAR2(100),
    category                VARCHAR2(100),
    category_id             VARCHAR2(100),
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    main_display            VARCHAR2(200),
    seller                  VARCHAR2(200),
    manufacturer            VARCHAR2(200),
    detail_option           VARCHAR2(1000),
    detail_option_price     VARCHAR2(1000)
);

CREATE TABLE product_images (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id              NUMBER NOT NULL,
    image                   BLOB NOT NULL,
    image_type              VARCHAR2(100),
    CONSTRAINT fk_product_image FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE product_detail_images (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id              NUMBER NOT NULL,
    image                   BLOB NOT NULL,
    image_type              VARCHAR2(100),
    CONSTRAINT fk_product_detail_image FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE posts (
    post_id                 NUMBER PRIMARY KEY,
    title                   VARCHAR2(300) NOT NULL,
    content                 CLOB NOT NULL,
    member_id               VARCHAR2(50),
    created_date            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_date            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    view_count              NUMBER(10) DEFAULT 0 NOT NULL,
    board_type              VARCHAR2(50),
    image                   BLOB,
    CONSTRAINT fk_post_member FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE comments (
    comment_id              NUMBER PRIMARY KEY,
    post_id                 NUMBER NOT NULL,
    member_id               VARCHAR2(50),
    content                 VARCHAR2(2000) NOT NULL,
    created_date            DATE DEFAULT SYSDATE NOT NULL,
    updated_date            DATE DEFAULT SYSDATE NOT NULL,
    like_count              NUMBER(10) DEFAULT 0 NOT NULL,
    parent_id               NUMBER,
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_id) REFERENCES comments(comment_id)
);

CREATE TABLE requests (
    request_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultant_name         VARCHAR2(100) NOT NULL,
    consultant_email        VARCHAR2(255) NOT NULL,
    consultation_type       VARCHAR2(100),
    consultant_password     VARCHAR2(255),
    consultant_message      VARCHAR2(4000) NOT NULL,
    request_date            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    answer                  VARCHAR2(4000),
    member_id               VARCHAR2(50),
    CONSTRAINT fk_request_member FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE order_info (
    order_id                NUMBER PRIMARY KEY,
    customer_id             VARCHAR2(50),
    customer_name           VARCHAR2(100) NOT NULL,
    product_id              VARCHAR2(1000) NOT NULL,
    quantity                NUMBER(10) NOT NULL,
    product_quantities      VARCHAR2(1000),
    detail_option           VARCHAR2(1000),
    total_price             NUMBER(12) NOT NULL,
    shipping_address        VARCHAR2(500) NOT NULL,
    payment_method          VARCHAR2(50) NOT NULL,
    bank_status             VARCHAR2(50),
    order_status            VARCHAR2(50),
    order_date              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    phone_number            VARCHAR2(30),
    email                   VARCHAR2(255),
    delivery_request        VARCHAR2(1000),
    delivery_date           TIMESTAMP,
    delivery_complete_date  TIMESTAMP,
    is_canceled             CHAR(1) DEFAULT 'N' NOT NULL,
    last_updated            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tracking_number         VARCHAR2(100),
    CONSTRAINT fk_order_member FOREIGN KEY (customer_id) REFERENCES member(id)
);

CREATE TABLE return_request (
    return_id               NUMBER PRIMARY KEY,
    order_id                NUMBER NOT NULL,
    member_id               VARCHAR2(50),
    reason_type             VARCHAR2(100) NOT NULL,
    reason_text             VARCHAR2(2000),
    request_date            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    product_id              VARCHAR2(1000),
    status                  VARCHAR2(50),
    reject_reason           VARCHAR2(1000),
    CONSTRAINT fk_return_order FOREIGN KEY (order_id) REFERENCES order_info(order_id),
    CONSTRAINT fk_return_member FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE return_image (
    image_id                NUMBER PRIMARY KEY,
    return_id               NUMBER NOT NULL,
    image_data              BLOB NOT NULL,
    image_name              VARCHAR2(500),
    upload_date             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_return_image FOREIGN KEY (return_id) REFERENCES return_request(return_id) ON DELETE CASCADE
);

CREATE TABLE review (
    review_id               NUMBER PRIMARY KEY,
    product_id              NUMBER NOT NULL,
    review_comment          VARCHAR2(2000) NOT NULL,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP,
    user_id                 VARCHAR2(50),
    user_name               VARCHAR2(100),
    rating                  NUMBER(1) NOT NULL,
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_review_member FOREIGN KEY (user_id) REFERENCES member(id)
);

CREATE TABLE review_image (
    image_id                NUMBER PRIMARY KEY,
    review_id               NUMBER NOT NULL,
    image_name              VARCHAR2(500),
    image_data              BLOB NOT NULL,
    upload_date             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_image FOREIGN KEY (review_id) REFERENCES review(review_id) ON DELETE CASCADE
);

CREATE SEQUENCE posts_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE comments_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE order_seq START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE return_seq START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE return_image_seq START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE review_seq START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE review_image_seq START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_display ON products(main_display);
CREATE INDEX idx_posts_created ON posts(created_date);
CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_orders_customer ON order_info(customer_id);
CREATE INDEX idx_reviews_product ON review(product_id);
